Avoid variable length arrays (VLAs)
While disabling VLA warnings is possible, using VLAs in C++ is discouraged due to portability concerns and potential security issues, especially if array sizes aren't explicitly validated. Although switching to dynamic allocation doesn't guarantee improved security on its own, it makes code more compliant with the C++ standard and improves compatibility with modern compilers like Clang.

Fix:

sctpthread.cpp:95:18: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
   95 |   uint8_t buffer[m_linkMtuSize];
      |                  ^~~~~~~~~~~~~

Signed-off-by: Alper Ak <alperyasinak1@gmail.com>