include bits/stdc++.h only when using libstdc++
We have other c++ runtime implementations e.g. llvm's libc++ which does
not provide this header bits/stdc++.h, therefore make sure that this
header is only included when using libstdc++

Fixes
| /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux/cannelloni/1.1.0/git/tcpthread.cpp:27:10: fatal error: 'bits/stdc++.h' file not found
|    27 | #include <bits/stdc++.h>
|       |          ^~~~~~~~~~~~~~~

Upstream-Status: Submitted [https://github.com/mguentner/cannelloni/pull/56]
Signed-off-by: Khem Raj <raj.khem@gmail.com>